set serveroutput on;

-- drop table if exist
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

/

-- create users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR(255)
);

INSERT INTO users (name) VALUES ('Archimedes');
INSERT INTO users (name) VALUES ('Euler');
INSERT INTO users (name) VALUES ('Leibniz');

/

-- simple cursor with temporary variables
DECLARE
    CURSOR cur_get_users IS
        SELECT id, name FROM users;
    
    tmp_id NUMBER;
    tmp_name VARCHAR(255);
BEGIN
    OPEN cur_get_users;
    LOOP
        FETCH cur_get_users INTO tmp_id, tmp_name;
        EXIT WHEN cur_get_users%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(tmp_id);
        DBMS_OUTPUT.PUT_LINE(tmp_name);
    
    END LOOP;
    CLOSE cur_get_users;
END;

/

-- simple cursor with row
DECLARE
    CURSOR cur_get_users IS
        SELECT id, name FROM users;
    
    tmp_row cur_get_users%ROWTYPE;
BEGIN
    OPEN cur_get_users;
    LOOP

        FETCH cur_get_users INTO tmp_row;
        EXIT WHEN cur_get_users%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(tmp_row.id);
        DBMS_OUTPUT.PUT_LINE(tmp_row.name);
    
    END LOOP;
    CLOSE cur_get_users;
END;
